name: teleconsult_app
description: TeleConsult Basic App (Doctor + Kiosk)
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.2
  permission_handler: ^12.0.1
  zego_uikit_prebuilt_call: ^4.19.2
  pdf: ^3.10.7
  path_provider: ^2.0.14
  url_launcher: ^6.1.12
  shared_preferences: ^2.1.1
  #flutter_vibrate: ^1.3.
  share_plus: 12.0.0
  whatsapp_share2: ^2.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
