import 'dart:io';
import 'package:path_provider/path_provider.dart';
import 'package:pdf/widgets.dart' as pw;

class PDFService {
  static Future<File> generatePrescription(String patientName, String diagnosis, String medicine) async {
    final pdf = pw.Document();
    pdf.addPage(
      pw.Page(
        build: (context) => pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Text('Prescription', style: pw.TextStyle(fontSize: 26)),
            pw.SizedBox(height: 12),
            pw.Text('Patient: $patientName'),
            pw.SizedBox(height: 8),
            pw.Text('Diagnosis: $diagnosis'),
            pw.SizedBox(height: 6),
            pw.Text('Medicine: $medicine'),
            pw.SizedBox(height: 20),
            pw.Text('Generated by TeleConsult Demo App'),
          ],
        ),
      ),
    );

    final dir = await getApplicationDocumentsDirectory();
    final file = File('${dir.path}/prescription_${DateTime.now().millisecondsSinceEpoch}.pdf');
    await file.writeAsBytes(await pdf.save());
    return file;
  }
}
